/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eni.m1.ia;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shirleyodon
 */
public class Fenetre extends javax.swing.JFrame {

    /**
     * Creates new form Fenetre
     */
    private DefaultTableModel model;
    private int compteur=0;
    public Fenetre() {
        initComponents();
        setLocationRelativeTo(null);
        initModel();
    }
    
    private void initModel(){
        model=(DefaultTableModel)resultTable.getModel();
        model.setRowCount(0);
        resultTable.setModel(model);
    }
    
    private void ajouterUneLigne(String numero, String rivG, String traversee, String rivD){
        model.addRow(new Object[]{
            numero, rivG, traversee, rivD
        });
        resultTable.setModel(model);
        compteur++;
    }
    
    private String numberToChar(int m, int c){
        String mis="", can="";
        for(int i=1; i<=m; i++) mis+="M";
        for(int i=1; i<=c; i++) can+="C";
        
        return mis+" "+can;
    }
    
    private String dansLeBateau(Etat pere, Etat fils){
        int m=0, c=0;
        if(pere.estAGauche()){
            m=fils.getMisD()-pere.getMisD();
            c=fils.getCanD()-pere.getCanD();
            return numberToChar(m, c)+" -->";
        }else{
            m=fils.getMisG()-pere.getMisG();
            c=fils.getCanG()-pere.getCanG();
            return "<-- "+numberToChar(m, c);
        }
    }
    
    private void afficherSolution(Etat solution){
        if(solution==null) JOptionPane.showMessageDialog(null, "Aucune solution trouvée !", "Erreur", JOptionPane.ERROR_MESSAGE);
        else{
            List<Etat> path=new ArrayList();
            Etat e=solution;
            
            while(e!=null){
                path.add(e);
                e=e.getPere();
            }
            
            int hauteur=path.size()-1;
            model.setRowCount(0);
            compteur=0;
            ajouterUneLigne("Début", numberToChar(path.get(hauteur).getMisG(), path.get(hauteur).getCanG()), "", numberToChar(path.get(hauteur).getMisD(), path.get(hauteur).getCanD()));
            
            for(int i=hauteur; i>=0; i--){
                Etat pere=path.get(i);
                
                if(pere.estArrive()) ajouterUneLigne("Fin", "", "", numberToChar(pere.getMisD(), pere.getCanD()));
                else if(i>=1){
                    Etat fils=path.get(i-1);
                    if(pere.estAGauche())
                        ajouterUneLigne(String.valueOf(compteur), numberToChar(fils.getMisG(), fils.getCanG()), dansLeBateau(pere, fils), numberToChar(pere.getMisD(), pere.getCanD()));
                    else
                        ajouterUneLigne(String.valueOf(compteur), numberToChar(pere.getMisG(), pere.getCanG()), dansLeBateau(pere, fils), numberToChar(fils.getMisD(), fils.getCanD()));
                }
            }
        }
    }
    
    private boolean estValide(JFormattedTextField formattedField){
        return formattedField.isEditValid();
    }
    
    private void eraseField(){
        leftMissionariesNumberField.setValue(null);
        leftCannibalsNumberField.setValue(null);
        rigthMissionariesNumberField.setValue(null);
        rightCannibalsNumberField.setValue(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        dataEntryPanel = new javax.swing.JPanel();
        missionariesNumberLabel = new javax.swing.JLabel();
        cannibalsNumberLabel = new javax.swing.JLabel();
        leftBankLabel = new javax.swing.JLabel();
        rigthtBankLabel = new javax.swing.JLabel();
        leftMissionariesNumberField = new javax.swing.JFormattedTextField();
        rigthMissionariesNumberField = new javax.swing.JFormattedTextField();
        leftCannibalsNumberField = new javax.swing.JFormattedTextField();
        rightCannibalsNumberField = new javax.swing.JFormattedTextField();
        startButton = new javax.swing.JButton();
        resultPanel = new javax.swing.JPanel();
        resultScrollPane = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Application");
        setResizable(false);

        bodyPanel.setBackground(new java.awt.Color(0, 142, 142));

        titlePanel.setBackground(new java.awt.Color(0, 142, 142));
        titlePanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));

        titleLabel.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("PROBLEME DES MISSIONNAIRES & CANNIBALES");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
            .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(titlePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 509, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
            .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        dataEntryPanel.setBackground(new java.awt.Color(0, 142, 142));
        dataEntryPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));

        missionariesNumberLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        missionariesNumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        missionariesNumberLabel.setText("Nombre missionnaire");

        cannibalsNumberLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cannibalsNumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        cannibalsNumberLabel.setText("Nombre cannibale");

        leftBankLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        leftBankLabel.setForeground(new java.awt.Color(255, 255, 255));
        leftBankLabel.setText("Rive gauche");

        rigthtBankLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rigthtBankLabel.setForeground(new java.awt.Color(255, 255, 255));
        rigthtBankLabel.setText("Rive droite");

        leftMissionariesNumberField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        leftMissionariesNumberField.setForeground(java.awt.Color.gray);
        try {
            leftMissionariesNumberField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        leftMissionariesNumberField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        leftMissionariesNumberField.setFont(new java.awt.Font("Source Code Pro", 1, 14)); // NOI18N

        rigthMissionariesNumberField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        rigthMissionariesNumberField.setForeground(java.awt.Color.gray);
        try {
            rigthMissionariesNumberField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        rigthMissionariesNumberField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rigthMissionariesNumberField.setFont(new java.awt.Font("Source Code Pro", 1, 14)); // NOI18N

        leftCannibalsNumberField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        leftCannibalsNumberField.setForeground(java.awt.Color.gray);
        try {
            leftCannibalsNumberField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        leftCannibalsNumberField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        leftCannibalsNumberField.setFont(new java.awt.Font("Source Code Pro", 1, 14)); // NOI18N

        rightCannibalsNumberField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        rightCannibalsNumberField.setForeground(java.awt.Color.gray);
        try {
            rightCannibalsNumberField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        rightCannibalsNumberField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rightCannibalsNumberField.setFont(new java.awt.Font("Source Code Pro", 1, 14)); // NOI18N

        startButton.setBackground(new java.awt.Color(255, 255, 255));
        startButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        startButton.setForeground(java.awt.Color.gray);
        startButton.setText("Lancer");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataEntryPanelLayout = new javax.swing.GroupLayout(dataEntryPanel);
        dataEntryPanel.setLayout(dataEntryPanelLayout);
        dataEntryPanelLayout.setHorizontalGroup(
            dataEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataEntryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(missionariesNumberLabel)
                    .addComponent(cannibalsNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(dataEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(leftMissionariesNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leftBankLabel)
                    .addComponent(leftCannibalsNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(dataEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rigthtBankLabel)
                    .addComponent(rigthMissionariesNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rightCannibalsNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(startButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dataEntryPanelLayout.setVerticalGroup(
            dataEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataEntryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leftBankLabel)
                    .addComponent(rigthtBankLabel))
                .addGap(26, 26, 26)
                .addGroup(dataEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(missionariesNumberLabel)
                    .addComponent(leftMissionariesNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rigthMissionariesNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dataEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rightCannibalsNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leftCannibalsNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cannibalsNumberLabel)
                    .addComponent(startButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        resultPanel.setBackground(new java.awt.Color(0, 142, 142));
        resultPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.white, java.awt.Color.white));

        resultTable.setFont(new java.awt.Font("Source Code Pro", 1, 14)); // NOI18N
        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "N° de traversée", "Rive gauche", "Traversée", "Rive droite"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        resultTable.setGridColor(java.awt.Color.lightGray);
        resultTable.setRowHeight(20);
        resultTable.setShowGrid(true);
        resultScrollPane.setViewportView(resultTable);

        javax.swing.GroupLayout resultPanelLayout = new javax.swing.GroupLayout(resultPanel);
        resultPanel.setLayout(resultPanelLayout);
        resultPanelLayout.setHorizontalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
            .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(resultScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE))
        );
        resultPanelLayout.setVerticalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
            .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(resultScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataEntryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bodyPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(resultPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dataEntryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyPanelLayout.createSequentialGroup()
                    .addContainerGap(230, Short.MAX_VALUE)
                    .addComponent(resultPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
        startButton.setEnabled(false);
        if(estValide(rigthMissionariesNumberField) && estValide(leftMissionariesNumberField)
          && estValide(rightCannibalsNumberField) && estValide(leftCannibalsNumberField)){
            try{
                int lmn= Integer.valueOf(leftMissionariesNumberField.getText()),
                    lcn= Integer.valueOf(leftCannibalsNumberField.getText()),
                    rmn= Integer.valueOf(rigthMissionariesNumberField.getText()),
                    rcn= Integer.valueOf(rightCannibalsNumberField.getText());
                Etat initial=new Etat(lmn, lcn, Position.GAUCHE, rmn, rcn);
                
                if(initial.etatValide()){
                    AlgorithmeBFS bfs=new AlgorithmeBFS();
                    afficherSolution(bfs.executerBFS(initial));
                    eraseField();
                }else{
                    String sms="Toutes les valeurs entrées doivent être positives ou nulles et le nombre de Missionnaires\n"
                            + "doit-être null ou au moins égal au nombre de canibales des deux cotés de la rive !";
                    JOptionPane.showMessageDialog(null, sms, "Données invalides", JOptionPane.ERROR_MESSAGE);
                }
            }catch(Exception ex){
                System.err.println(ex);
            }
        }
        startButton.setEnabled(true);
    }//GEN-LAST:event_startButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fenetre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JLabel cannibalsNumberLabel;
    private javax.swing.JPanel dataEntryPanel;
    private javax.swing.JLabel leftBankLabel;
    private javax.swing.JFormattedTextField leftCannibalsNumberField;
    private javax.swing.JFormattedTextField leftMissionariesNumberField;
    private javax.swing.JLabel missionariesNumberLabel;
    private javax.swing.JPanel resultPanel;
    private javax.swing.JScrollPane resultScrollPane;
    private javax.swing.JTable resultTable;
    private javax.swing.JFormattedTextField rightCannibalsNumberField;
    private javax.swing.JFormattedTextField rigthMissionariesNumberField;
    private javax.swing.JLabel rigthtBankLabel;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
